Project: todolist interactive-list
wwwdrt/todolist pull request #4
Opened 2023-05-12 20:59 UTC by wwwdrt

# 👋 Hey CRs

> I'm looking forward to your feedback 🚀

Please feel free to reach out to me on Slack anytime. You can send me a direct message or give me a call. If you choose to call, please introduce yourself so I know who I'm speaking with. I'm here to help, so don't hesitate to get in touch 😁

<div align="center">
  <img src="https://media2.giphy.com/media/13HgwGsXF0aiGY/giphy.gif?cid=ecf05e47drdxamgqh5qs2m9cwb2iozsx0q3c5veum57xf0j2&ep=v1_gifs_search&rid=giphy.gif&ct=g" />

### Latest project 🔥"[Secret Menu API](https://github.com/wwwdrt/secret_menu_api)"
</div>

# ⚒️ Development

> Clear explanation of the approach I took in the project 👇

## 🗒️Index.js

- This file serves as the entry point of my application.
- It imports and initializes different components to work together.
- The components include Data, Create, Read, Update, and Destroy.

## 🗒️Data.js

- This component manages the todo list data.
- It handles rendering tasks on the webpage and updating the data accordingly.
- It provides methods to add, update, and delete tasks.
- The data is stored in the browser's localStorage for persistence.

## 🗒️Create.js

- This component handles the creation of new tasks.
- It listens for a form submission event and adds a new task to the Data component.
- When a user submits a task description, it is added to the todo list.

## 🗒️Read.js

- This component is responsible for reading and updating task data.
- It listens for user input changes and updates the task description in the Data component accordingly.
- When a user edits a task description, it reflects the changes in the todo list.

## 🗒️Update.js

- This component handles the update of task descriptions.
- It listens for input changes on individual tasks and updates the corresponding task in the Data component.
- When a user modifies a task's description, it triggers an update in the todo list.

## 🗒️Destroy.js

- This component handles the deletion of tasks.
- It listens for a "Clear All" button click and removes all tasks from the Data component.
- When a user clicks the "Clear All" button, it removes all tasks from the todo list.

<div align="center">

# Take care 🤝
</div>

2023-05-12 21:44 UTC, Ginohmk requested changes
Hi @wwwdrt , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![you-are-near](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Properly Organised codebase
- Good use of class


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Checking the requirements and following it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 21:44 UTC, Ginohmk commented on src/components/Data.js
- @wwwdrt Good job on organizing your code, however from the requirements, you are to use an `Array filter method` to clear completed tasks when the `Clear all completed` button is, While I clicked on the button it cleared all tasks on the todo-list, which is not supposed to be. 

    - Please refer to the video below for clarification. 

[Screencast from 05-12-2023 10:23:54 PM.webm](https://github.com/wwwdrt/todolist/assets/58771507/b40e2fa5-8a26-4505-9a7d-f336b079f26f)

2023-05-12 21:44 UTC, Ginohmk commented on src/components/Data.js
> +        this.updateTaskStatus(index);
-  Hi @wwwdrt From your code, you made use of a `button` instead of a `check box `for toggling between  the `completed task` and not `completed task `, I advise you use a checkbox so you can use the event listener 'change`
- Also as the requirement stated: `Add event listener to the checkbox (change).`, 

**In summary**   
- Make use of a check box and add Evenet listener of `change`

2023-05-12 21:54 UTC, wwwdrt commented on src/components/Data.js
👋 You are right, thank you!

2023-05-12 22:06 UTC, wwwdrt commented on src/components/Data.js
> +        this.updateTaskStatus(index);
I spent quite a bit of time trying to style that checkbox, but no matter what I did the styles where never applied. 

After struggling with it for a while, I decided it was best to move on and explore other options for implementation. I didn't want to waste any more time on a single element when there were other aspects of the project that needed attention. 

So, I made the choice to prioritize efficiency and continue with a different approach.

- [ ] I will style it tonight 🌜

2023-05-12 22:09 UTC, Ginohmk commented on src/components/Data.js
> +        this.updateTaskStatus(index);
@wwwdrt  You can have a read at this [Styling Checkbox](https://moderncss.dev/pure-css-custom-checkbox-style/) , it , might be helpeful

2023-05-14 04:35 UTC, franclobo approved these changes
Hi @wwwdrt, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/wwwdrt/todolist/assets/58642949/2a90e59f-a166-4122-baaa-80713488e788)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- All completed tasks work as expected ✔️ 
- Method filter used 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-14 04:38 UTC, merged